# Site settings
title: Spirulinazur
email: pelegrijulien@hotmail.fr
description: "A website to present Spirulinazur amazing products ! "
keywords:
- Spirulinazur

# URL
url: "https://wiredcraft.github.io/jekyll-basics"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
# google_tag_manager: GTM-XXXXXX
# google_analytics: UA-XXXXXXX-X

# SEO
twitter: wiredcraft
facebook: https://www.facebook.com/teamwiredcraft
logo: /assets/logo.png
image: /assets/logo.png
social:
  - https://www.facebook.com/teamwiredcraft
  - https://twitter.com/wiredcraft
  - https://www.linkedin.com/company/wiredcraft
  - https://github.com/wiredcraft
  - https://weibo.com/1970385015/


# generate social links in footer
social_links:
  facebook: spirulinazur
  instagram: spirulinazur

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ['README.md', 'Makefile']

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post

# Plugins
plugins:
- jekyll-sitemap

# Multiligual
lang:
  - en
  - fr

# Version (helps with force reloading assets)
version: sparkle

# Jekyll+ (not useful if you're running on GitHub pages)
# jekyllplus: Wiredcraft/jekyll-basics/master
